-- PSL auction admin improvements
-- Run this in Supabase SQL Editor before using the new admin actions.

alter table if exists public.team_players
  add column if not exists created_at timestamptz not null default now();

create table if not exists public.auction_events (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(id) on delete cascade,
  team_id bigint references public.teams(id) on delete set null,
  event_type text not null check (event_type in ('sold', 'reopened', 'unsold', 'send_to_end', 'bid_reset', 'bid_undo')),
  amount bigint,
  note text,
  created_at timestamptz not null default now()
);

create index if not exists idx_auction_events_created_at on public.auction_events(created_at desc);
create index if not exists idx_auction_events_player_id on public.auction_events(player_id);
create index if not exists idx_team_players_created_at on public.team_players(created_at desc);

create or replace function public.reset_auction_state()
returns void
language plpgsql
as $$
begin
  update public.auction_state
  set current_player_id = null,
      current_highest_bid = null,
      current_highest_team_id = null,
      status = 'idle',
      ends_at = null,
      timer_seconds = 60
  where id = 1;
end;
$$;

create or replace function public.admin_sold_current_player()
returns void
language plpgsql
as $$
declare
  v_auction public.auction_state%rowtype;
  v_team public.teams%rowtype;
  v_player public.players%rowtype;
  v_squad_count integer;
  v_remaining_slots_after_win integer;
  v_minimum_budget_to_keep bigint;
  v_budget_after_win bigint;
begin
  select * into v_auction from public.auction_state where id = 1 for update;
  if v_auction.current_player_id is null then
    raise exception 'No current player selected';
  end if;
  if v_auction.current_highest_team_id is null or v_auction.current_highest_bid is null then
    raise exception 'Cannot mark sold without a leading team and bid';
  end if;

  select * into v_player from public.players where id = v_auction.current_player_id for update;
  select * into v_team from public.teams where id = v_auction.current_highest_team_id for update;
  if v_team.id is null then
    raise exception 'Winning team not found';
  end if;

  select count(*) into v_squad_count from public.team_players where team_id = v_team.id;
  if v_squad_count >= coalesce(v_team.max_players, 12) then
    raise exception 'Winning team squad is already full';
  end if;

  if coalesce(v_team.budget_remaining, 0) < v_auction.current_highest_bid then
    raise exception 'Winning team does not have enough budget';
  end if;

  v_remaining_slots_after_win := coalesce(v_team.max_players, 12) - (v_squad_count + 1);
  v_minimum_budget_to_keep := greatest(v_remaining_slots_after_win, 0) * 5000000;
  v_budget_after_win := coalesce(v_team.budget_remaining, 0) - v_auction.current_highest_bid;

  if v_budget_after_win < v_minimum_budget_to_keep then
    raise exception 'Winning team must keep enough budget for remaining slots';
  end if;

  update public.players
  set status = 'sold',
      sold_to_team_id = v_team.id,
      sold_price = v_auction.current_highest_bid
  where id = v_player.id;

  insert into public.team_players(team_id, player_id, bought_price)
  values (v_team.id, v_player.id, v_auction.current_highest_bid);

  update public.teams
  set budget_remaining = v_budget_after_win
  where id = v_team.id;

  insert into public.auction_events(player_id, team_id, event_type, amount)
  values (v_player.id, v_team.id, 'sold', v_auction.current_highest_bid);

  perform public.reset_auction_state();
end;
$$;

create or replace function public.admin_reopen_player(p_player_id bigint)
returns void
language plpgsql
as $$
declare
  v_player public.players%rowtype;
  v_team public.teams%rowtype;
  v_latest_team_player public.team_players%rowtype;
begin
  select * into v_player from public.players where id = p_player_id for update;
  if v_player.id is null then
    raise exception 'Player not found';
  end if;
  if v_player.status <> 'sold' then
    raise exception 'Only sold players can be reopened';
  end if;

  select * into v_team from public.teams where id = v_player.sold_to_team_id for update;
  if v_team.id is null then
    raise exception 'Winning team not found';
  end if;

  select * into v_latest_team_player
  from public.team_players
  where player_id = p_player_id and team_id = v_player.sold_to_team_id
  order by id desc
  limit 1
  for update;

  if v_latest_team_player.id is null then
    raise exception 'Team roster record not found';
  end if;

  update public.teams
  set budget_remaining = coalesce(budget_remaining, 0) + coalesce(v_player.sold_price, 0)
  where id = v_team.id;

  delete from public.team_players where id = v_latest_team_player.id;
  delete from public.bids where player_id = p_player_id;

  update public.players
  set status = 'available',
      sold_to_team_id = null,
      sold_price = null
  where id = p_player_id;

  insert into public.auction_events(player_id, team_id, event_type, amount)
  values (p_player_id, v_team.id, 'reopened', v_player.sold_price);
end;
$$;

create or replace function public.admin_undo_last_bid()
returns void
language plpgsql
as $$
declare
  v_auction public.auction_state%rowtype;
  v_last_bid public.bids%rowtype;
  v_next_bid public.bids%rowtype;
begin
  select * into v_auction from public.auction_state where id = 1 for update;
  if v_auction.current_player_id is null then
    raise exception 'No current player selected';
  end if;

  select * into v_last_bid from public.bids where player_id = v_auction.current_player_id order by id desc limit 1 for update;
  if v_last_bid.id is null then
    raise exception 'No bids to undo';
  end if;

  delete from public.bids where id = v_last_bid.id;

  select * into v_next_bid from public.bids where player_id = v_auction.current_player_id order by id desc limit 1;

  update public.auction_state
  set current_highest_bid = v_next_bid.bid_amount,
      current_highest_team_id = v_next_bid.team_id
  where id = 1;

  insert into public.auction_events(player_id, team_id, event_type, amount, note)
  values (v_auction.current_player_id, v_last_bid.team_id, 'bid_undo', v_last_bid.bid_amount, 'Last bid removed');
end;
$$;

create or replace function public.admin_reset_current_player_bidding()
returns void
language plpgsql
as $$
declare
  v_auction public.auction_state%rowtype;
begin
  select * into v_auction from public.auction_state where id = 1 for update;
  if v_auction.current_player_id is null then
    raise exception 'No current player selected';
  end if;

  delete from public.bids where player_id = v_auction.current_player_id;

  update public.auction_state
  set current_highest_bid = null,
      current_highest_team_id = null,
      status = 'paused',
      ends_at = null,
      timer_seconds = 60
  where id = 1;

  insert into public.auction_events(player_id, event_type, note)
  values (v_auction.current_player_id, 'bid_reset', 'Bidding reset for current player');
end;
$$;

create or replace function public.admin_mark_unsold_current_player()
returns void
language plpgsql
as $$
declare
  v_auction public.auction_state%rowtype;
begin
  select * into v_auction from public.auction_state where id = 1 for update;
  if v_auction.current_player_id is null then
    raise exception 'No current player selected';
  end if;
  if v_auction.current_highest_team_id is not null then
    raise exception 'Cannot mark unsold while a team is leading';
  end if;

  delete from public.bids where player_id = v_auction.current_player_id;

  update public.players
  set status = 'unsold',
      sold_to_team_id = null,
      sold_price = null
  where id = v_auction.current_player_id;

  insert into public.auction_events(player_id, event_type)
  values (v_auction.current_player_id, 'unsold');

  perform public.reset_auction_state();
end;
$$;

create or replace function public.admin_send_current_player_to_end()
returns void
language plpgsql
as $$
declare
  v_auction public.auction_state%rowtype;
  v_max_order bigint;
begin
  select * into v_auction from public.auction_state where id = 1 for update;
  if v_auction.current_player_id is null then
    raise exception 'No current player selected';
  end if;
  if v_auction.current_highest_team_id is not null then
    raise exception 'Cannot send to end while a team is leading';
  end if;

  select coalesce(max(queue_order), 0) into v_max_order from public.players;

  update public.players
  set queue_order = v_max_order + 1
  where id = v_auction.current_player_id;

  insert into public.auction_events(player_id, event_type)
  values (v_auction.current_player_id, 'send_to_end');

  perform public.reset_auction_state();
end;
$$;

-- Optional: if players.status has a strict check constraint, add 'unsold' to that constraint manually.
